DROP DATABASE IF EXISTS express_react;
CREATE DATABASE express_react;
USE DATABASE express_react;

CREATE TABLE blogs(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100),
    content VARCHAR(100),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
);